name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcharts'
    - name: qmake
      run: qmake GymAssistant.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler && make qmake_all
    - name: make
      run: make -f Makefile all -j4
    - name: deploy
      run: macdeployqt ./build/App.app/ -dmg
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: App.dmg
        path: ./build/App.dmg
