name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: qmake
      run: qmake GitsSerializer.pro -spec macx-clang CONFIG+=x86_64 && make qmake_all
    - name: make
      run: make -f Makefile all -j4
